version: "3.9"
services:
  exchange:
    build: ./exchange
    container_name: exchange
    environment:
      - SQLITE_PATH=/app/exchange.db
      - REDIS_HOST=redis
      - REDIS_DB=0
      - POLICY_PATH=/app/policy/policy.yaml
      - HMAC_SECRET=phoenyra_demo_secret
    volumes:
      - ./policy:/app/policy:ro
    ports:
      - "9000:9000"
    depends_on:
      - redis
  webapp:
    build: ./webapp
    container_name: webapp
    environment:
      - EXCHANGE_BASE_URL=http://exchange:9000
      - API_KEY=demo
      - HMAC_SECRET=phoenyra_demo_secret
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app
    depends_on:
      - exchange
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - exchange
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_UNIFIED_ALERTING_ENABLED=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
