openapi: 3.0.3
info:
  title: Phoenyra Grid API
  version: 0.1.0
servers:
  - url: http://localhost:9501
paths:
  /grid/state:
    get:
      summary: Current grid state snapshot
      parameters:
        - in: query
          name: area
          schema: { type: string, example: "AT" }
      responses:
        "200":
          description: Grid state
          content:
            application/json:
              schema:
                type: object
                properties:
                  freq_hz: { type: number, example: 49.98 }
                  load_mw: { type: number }
                  tie_lines:
                    type: array
                    items:
                      type: object
                      properties:
                        name: { type: string }
                        flow_mw: { type: number }
                  congestion_index: { type: number, example: 0.2 }
  /grid/constraints:
    get:
      summary: Planned constraints and redispatch signals
      parameters:
        - in: query
          name: window
          schema: { type: string, example: "PT1H" }
      responses:
        "200":
          description: Constraints
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        ts: { type: string, format: date-time }
                        type: { type: string, example: "redispatch|maintenance" }
                        detail: { type: string }
